---
title: "Planejamento e Análise de Experimentos I"
author:
  - name: Prof. Dr. Juliano Bortolini
    email: profjulianobortolini@gmail.com
    url: http://www.julianobortolini.com.br
    affiliations:
      - name: Universidade Federal de Mato Grosso
format:
  html:
    embed-resources: true
engine: knitr
---

*Bacharelado em Estatística - UFMT*

*Período letivo: 2024/2*


### Lista de exercícios 2

 

1. (UFLA, adaptado) Um experimento foi conduzido para verificar a viabilidade do plantio de palmito na região de Lavras, MG, sob quatro diferentes ambientes de plantio: **sob eucalipto, sob mata, sob pinus e a pleno sol**. Foram medidas as alturas das plantas palmeiras (em cm) em **cinco repetições** para cada tratamento. Os dados coletados são apresentados na tabela abaixo:

| Tratamento  | Repetição 1 | Repetição 2 | Repetição 3 | Repetição 4 | Repetição 5 |
|------------|------------|------------|------------|------------|------------|
| Eucalipto  | 37         | 51         | 42         | 57         | 55         |
| Mata       | 44         | 62         | 40         | 71         | 55         |
| Pinus      | 56         | 58         | 62         | 70         | 65         |
| Pleno Sol  | 53         | 33         | 42         | 38         | 35         |

a) Aplique o **teste F** e interprete os resultados.
b) Realize o teste de Tukey, ao nível de $5\%$ de significância, para verificar quais efeitos dos tratamentos diferem entre si.


2. (UFLA, adaptado) Um experimento foi conduzido no **delineamento inteiramente casualizado (DIC)**, com **quatro repetições**, para avaliar a altura de plantas da espécie florestal **acácia** (*Acacia holocericea*) submetidas a diferentes substratos para formação de mudas. Os tratamentos e os valores de altura de planta (em cm) foram registrados na seguinte tabela:

| Substratos  | Rep. 1 | Rep. 2 | Rep. 3 | Rep. 4 |
|------------|--------|--------|--------|--------|
| CaC+EB     | 18,2   | 16,4   | 20,5   | 19,4   |
| CaC+EA     | 12,8   | 14,5   | 10,3   | 11,5   |
| HM         | 21,8   | 19,3   | 24,5   | 22,6   |
| Cap+EA     | 14,8   | 16,4   | 12,3   | 13,7   |
| Cap+EB     | 13,0   | 11,2   | 15,4   | 12,6   |
| Plantmax   | 16,0   | 14,2   | 18,1   | 16,4   |

a) Aplique o **teste F** e interprete os resultados.
b) Realize o teste de Tukey, ao nível de $5\%$ de significância, para verificar quais efeitos dos tratamentos diferem entre si.




------------------------------------------------------------------------

::: {style="text-align: center;"}
[\@profjulianobortolini](https://instagram.com/profjulianobortolini)      [www.julianobortolini.com.br](http://www.julianobortolini.com.br)      [linkedin](https://linkedin.com/in/julianobortolini)      [github](https://github.com/julianobortolini)       [lattes](http://lattes.cnpq.br/6210909768845403)
:::
