---
title: "Planejamento e AnûÀlise de Experimentos I"
author:
  - name: Prof. Dr. Juliano Bortolini
    email: profjulianobortolini@gmail.com
    url: http://www.julianobortolini.com.br
    affiliations:
      - name: Universidade Federal de Mato Grosso
format:
  pdf:
    embed-resources: true
engine: knitr
---

*Bacharelado em EstatûÙstica - UFMT*

*PerûÙodo letivo: 2024/2*


### Prova 1 - 10-3-25



1. Um experimento foi conduzido no **delineamento inteiramente casualizado (DIC)**, com **trûˆs repetiûÏûçes**, para avaliar a altura de plantas da espûˋcie florestal **acûÀcia** (*Acacia holocericea*) submetidas a diferentes substratos para formaûÏûÈo de mudas. Os tratamentos e os valores de altura de planta (em cm) foram registrados na seguinte tabela (**dados fictûÙcios**):


    | Substratos  | Rep. 1 | Rep. 2 | Rep. 3 |
    |------------|--------|--------|--------|
    | CaC+EB     | 18   | 16   | 20   |
    | CaC+EA     | 12   | 13   | 11   |
    | HM         | 20   | 19   | 24   |
    | CaP+EB     | 13   | 12   | 14   |
    | CaP+EA     | 14   | 14   | 11   |
    | Plantmax   | 15   | 16   | 17   |

a) (**0,125**) Quais sûÈo as fontes de variaûÏûçes nesse experimento?
b) (**0,125**) Quais sûÈo os graus de liberdade para cada fonte de variaûÏûÈo?
c) (**1,00**) Calcule as somas de quadrados total, tratamento e erro (ou resûÙduo).
d) (**0,50**) Calcule o quadrado mûˋdio para tratamento e erro (ou resûÙduo).
e) (**0,25**) Quais sûÈo as hipû°teses nula e alternativa para o teste F?
f) (**0,25**) Escreva a tabela da anûÀlise de variûÂncia (teste F) e calcule o valor da estatûÙstica do teste F e interprete o resultado.
g) (**0,25**) Calcule as mûˋdias dos tratamentos.
h) (**1,00**) Realize o teste de Tukey, ao nûÙvel de $5\%$ de significûÂncia, para verificar quais efeitos dos tratamentos diferem entre si e interprete os resultados.
i) (**0,25**) Qual contraste pode ser definido para comparar os efeitos de Cac e CaP? Realize o teste t para esse contraste. Utilize o valor do quantil superior da distribuiûÏûÈo t igual a $1,96$ (aproximaûÏûÈo pela normal).
j) (**0,25**) Qual contraste pode ser definido para comparar os efeitos de EB e EA? Esse contraste ûˋ ortogonal ao anterior?


2. Um experimento foi realizado para verificar o efeito de antiparasitûÀrios no peso dos animais.

    Tabela. Peso dos animais por tratamento e repetiûÏûÈo (**dados fictûÙcios**).
    
    | Tratamento  | 1   | 2   |
    |------------|----|----|
    | Controle   | 279 | 240 |
    | Neguvon    | 330 | 314 |
    | Methiridim | 315 | 304 |
    | TH         | 298 | 289 |
    | Haloxon    | 286 | 273 |


a) (**2,00**) Aplique o **teste F** e interprete os resultados.
b) (**1,00**)  Realize o teste Dunnett, ao nûÙvel de $5\%$ de significûÂncia, para verificar quais efeitos dos tratamentos diferem com o controle.


3. (**1,50**) Explique o que ûˋ variaûÏûÈo total, entre os tratamentos e dentro dos tratamentos.

4. (**1,50**) Preencha as lacunas:

    O delineamento \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  ûˋ indicado para experimentos em que as unidades experimentais sûÈo \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ . Em um experimento balanceado, o nû¤mero de \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_  deve ser igual entre os tratamentos, o que aumenta a precisûÈo dos resultados. A hipû°tese nula do teste F para efeitos de tratamentos ûˋ que todos os efeitos sûÈo \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ . Para que a anûÀlise de variûÂncia seja vûÀlida, os resûÙduos devem apresentar distribuiûÏûÈo \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ , e os erros devem ser \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ , com variûÂncia \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ . Caso seja rejeitado o teste F da anûÀlise de variûÂncia para efeitos de tratamentos, ûˋ necessûÀrio realizar os testes \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ .


    <!-- **Sugestûçes de palavras:** tratamentos, diferentes, blocos casualizados, normal, prû°ximos, constante, comparaûÏûçes mû¤ltiplas, inteiramente casualizado, repetiûÏûçes, equilibrada, iguais, linear, nûÈo-paramûˋtricos, homogûˆneas, balanceado, dependentes, quadrado latino, heterogûˆneas, assintû°ticos, nula, grau de liberdade, independentes, *entre outras*. -->


<!-- ------------------------------------------------------------------------ -->

<!-- ::: {style="text-align: center;"} -->
<!-- [\@profjulianobortolini](https://instagram.com/profjulianobortolini) ô  ô  ô [www.julianobortolini.com.br](http://www.julianobortolini.com.br) ô  ô  ô [linkedin](https://linkedin.com/in/julianobortolini) ô  ô  ô [github](https://github.com/julianobortolini) ô  ô  ô  [lattes](http://lattes.cnpq.br/6210909768845403) -->
<!-- ::: -->
